[package]
name = "leafc"
version = "0.0.1"
authors = ["virusdownloader7@gmail.com"]

[lib]
name = "leafc"
path = "src/lib.rs"

[dependencies]
backtrace = "0.3"
log = "0.4.3"

[[bin]]
name = "leafc"
path = "src/leafc/leafc.rs"