[package]
name = "leafc"
version = "0.0.1"
authors = ["virusdownloader7@gmail.com"]

[[bin]]
name = "leafc"
path = "src/main.rs"

[dependencies]
log = "0.4.3"
fern = "0.5.6"
clap = "2.32.0"
leafvm = { path = "../../leafvm" }
libleafc = { path = "../../leafc" }